// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"

	models "github.com/doug-benn/go-server-starter/models"
)

type Querier interface {
	CompleteTodo(ctx context.Context, arg CompleteTodoParams) (models.Todo, error)
	CreateTodo(ctx context.Context, arg CreateTodoParams) (models.Todo, error)
	DeleteTodo(ctx context.Context, id int32) error
	GetTodo(ctx context.Context, id int32) (models.Todo, error)
	ListTodos(ctx context.Context) ([]models.Todo, error)
	UpdateTodo(ctx context.Context, arg UpdateTodoParams) (models.Todo, error)
}

var _ Querier = (*Queries)(nil)
