// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: todo.sql

package repository

import (
	"context"
	"time"

	models "github.com/doug-benn/go-server-starter/models"
)

const completeTodo = `-- name: CompleteTodo :one
UPDATE todos
SET completed = true, updated_at = $1
WHERE id = $2
RETURNING id, title, description, completed, created_at, updated_at
`

type CompleteTodoParams struct {
	UpdatedAt time.Time `json:"updated_at"`
	ID        int32     `json:"id"`
}

func (q *Queries) CompleteTodo(ctx context.Context, arg CompleteTodoParams) (models.Todo, error) {
	row := q.db.QueryRow(ctx, completeTodo, arg.UpdatedAt, arg.ID)
	var i models.Todo
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Completed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTodo = `-- name: CreateTodo :one
INSERT INTO todos (title, description, completed, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, title, description, completed, created_at, updated_at
`

type CreateTodoParams struct {
	Title       string    `json:"title"`
	Description string    `json:"description"`
	Completed   bool      `json:"completed"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) CreateTodo(ctx context.Context, arg CreateTodoParams) (models.Todo, error) {
	row := q.db.QueryRow(ctx, createTodo,
		arg.Title,
		arg.Description,
		arg.Completed,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i models.Todo
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Completed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTodo = `-- name: DeleteTodo :exec
DELETE FROM todos
WHERE id = $1
`

func (q *Queries) DeleteTodo(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteTodo, id)
	return err
}

const getTodo = `-- name: GetTodo :one
SELECT id, title, description, completed, created_at, updated_at
FROM todos
WHERE id = $1
`

func (q *Queries) GetTodo(ctx context.Context, id int32) (models.Todo, error) {
	row := q.db.QueryRow(ctx, getTodo, id)
	var i models.Todo
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Completed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTodos = `-- name: ListTodos :many
SELECT id, title, description, completed, created_at, updated_at
FROM todos
ORDER BY created_at DESC
`

func (q *Queries) ListTodos(ctx context.Context) ([]models.Todo, error) {
	rows, err := q.db.Query(ctx, listTodos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []models.Todo
	for rows.Next() {
		var i models.Todo
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Completed,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTodo = `-- name: UpdateTodo :one
UPDATE todos
SET title = $1, description = $2, completed = $3, updated_at = $4
WHERE id = $5
RETURNING id, title, description, completed, created_at, updated_at
`

type UpdateTodoParams struct {
	Title       string    `json:"title"`
	Description string    `json:"description"`
	Completed   bool      `json:"completed"`
	UpdatedAt   time.Time `json:"updated_at"`
	ID          int32     `json:"id"`
}

func (q *Queries) UpdateTodo(ctx context.Context, arg UpdateTodoParams) (models.Todo, error) {
	row := q.db.QueryRow(ctx, updateTodo,
		arg.Title,
		arg.Description,
		arg.Completed,
		arg.UpdatedAt,
		arg.ID,
	)
	var i models.Todo
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Completed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
